from pathlib import Path
p = Path('/tmp/appfix/electron/main.cjs')
text = p.read_text(encoding='utf-8')

# insert net require
text = text.replace('const { spawn } = require("child_process");\n', 'const { spawn } = require("child_process");\nconst net = require("net");\n')

# helper insertion after wait
old = 'function wait(ms) {\n  return new Promise((resolve) => setTimeout(resolve, ms));\n}\n\nfunction runFfmpeg(args, options = {}) {\n'
new = '''function wait(ms) {\n  return new Promise((resolve) => setTimeout(resolve, ms));\n}\n\nfunction normalizeFilterPath(filePath) {\n  return safeText(filePath).replace(/\\/g, "/").replace(/:/g, "\\:").replace(/'/g, "\\'");\n}\n\nfunction isPortInUse(port, host = "127.0.0.1") {\n  return new Promise((resolve) => {\n    const socket = new net.Socket();\n\n    const done = (value) => {\n      try { socket.destroy(); } catch {}\n      resolve(value);\n    };\n\n    socket.setTimeout(800);\n    socket.once("connect", () => done(true));\n    socket.once("timeout", () => done(false));\n    socket.once("error", () => done(false));\n    socket.connect(port, host);\n  });\n}\n\nfunction getUserDataDir() {\n  return path.join(app.getPath("userData"), "bgm-library");\n}\n\nfunction getBgmManifestPath() {\n  return path.join(getUserDataDir(), "bgm-assets.json");\n}\n\nfunction ensureBgmLibraryDir() {\n  const dir = getUserDataDir();\n  fs.mkdirSync(dir, { recursive: true });\n  return dir;\n}\n\nfunction normalizeBgmId(value) {\n  const raw = safeText(value).toLowerCase();\n  const cleaned = raw\n    .normalize("NFD")\n    .replace(/[\u0300-\u036f]/g, "")\n    .replace(/[^a-z0-9]+/g, "_")\n    .replace(/^_+|_+$/g, "")\n    .replace(/_+/g, "_");\n  return cleaned || `bgm_${Date.now()}`;\n}\n\nfunction readBgmAssets() {\n  try {\n    const file = getBgmManifestPath();\n    if (!fs.existsSync(file)) return [];\n    const parsed = JSON.parse(fs.readFileSync(file, "utf8") || "[]");\n    return Array.isArray(parsed) ? parsed : [];\n  } catch {\n    return [];\n  }\n}\n\nfunction writeBgmAssets(assets) {\n  ensureBgmLibraryDir();\n  fs.writeFileSync(getBgmManifestPath(), JSON.stringify(Array.isArray(assets) ? assets : [], null, 2), "utf8");\n}\n\nfunction normalizeBgmAsset(raw = {}) {\n  const fileName = safeText(raw.fileName || path.basename(safeText(raw.filePath || "")));\n  const label = safeText(raw.label || raw.id || fileName || "Untitled BGM");\n  return {\n    id: normalizeBgmId(raw.id || label || fileName),\n    label,\n    fileName,\n    filePath: safeText(raw.filePath),\n    category: safeText(raw.category),\n    defaultVolume: Number.isFinite(Number(raw.defaultVolume)) ? Number(raw.defaultVolume) : 0.25,\n    tags: Array.isArray(raw.tags) ? raw.tags.map((x) => safeText(x).toLowerCase()).filter(Boolean) : [],\n    createdAt: safeText(raw.createdAt || new Date().toISOString()),\n    updatedAt: safeText(raw.updatedAt || new Date().toISOString())\n  };\n}\n\nfunction uniqueFilePath(filePath) {\n  const parsed = path.parse(filePath);\n  let candidate = filePath;\n  let index = 1;\n  while (fs.existsSync(candidate)) {\n    candidate = path.join(parsed.dir, `${parsed.name}_${index}${parsed.ext}`);\n    index += 1;\n  }\n  return candidate;\n}\n\nfunction runFfmpeg(args, options = {}) {\n'''
text = text.replace(old, new)

# patch startBackend
old = '''async function startBackend() {\n  if (backendProcess && !backendProcess.killed) return;\n  const serverEntry = getServerEntry();\n  if (!fs.existsSync(serverEntry)) {\n    log(`server entry not found: ${serverEntry}`);\n    return;\n  }\n\n  log("APP STARTING...");\n  log("startBackend()");\n  log(`isDev = ${String(isDev)}`);\n  log(`command = ${process.execPath}`);\n  log(`serverEntry = ${serverEntry}`);\n\n  backendProcess = spawn(process.execPath, [serverEntry], {\n'''
new = '''async function startBackend() {\n  if (backendProcess && !backendProcess.killed) return;\n\n  const host = process.env.HOST || "127.0.0.1";\n  const port = Number(process.env.PORT || 3030);\n  const alreadyRunning = await isPortInUse(port, host);\n  if (alreadyRunning) {\n    log(`Backend already running at http://${host}:${port}, skip spawn.`);\n    return;\n  }\n\n  const serverEntry = getServerEntry();\n  if (!fs.existsSync(serverEntry)) {\n    log(`server entry not found: ${serverEntry}`);\n    return;\n  }\n\n  log("APP STARTING...");\n  log("startBackend()");\n  log(`isDev = ${String(isDev)}`);\n  log(`command = ${process.execPath}`);\n  log(`serverEntry = ${serverEntry}`);\n\n  backendProcess = spawn(process.execPath, [serverEntry], {\n'''
text = text.replace(old, new)
text = text.replace('  log("Backend ready at http://127.0.0.1:3030");\n}', '  log(`Backend ready at http://${host}:${port}`);\n}')

# patch subtitle path usage
text = text.replace("`subtitles='${quoteFilterPath(finalSrtPath)}':force_style='FontName=Arial,FontSize=22,PrimaryColour=&H00FFFFFF,OutlineColour=&H00111111,BorderStyle=1,Outline=1,Shadow=0,Alignment=2,MarginV=36'`", "`subtitles='${normalizeFilterPath(finalSrtPath)}':charenc=UTF-8:force_style='FontName=Arial,FontSize=22,PrimaryColour=&H00FFFFFF,OutlineColour=&H00111111,BorderStyle=1,Outline=2,Shadow=0,Alignment=2,MarginV=36'`")

# replace compose audio mixing block to multi-bed support
old = '''  if (!musicBeds.length) {\n    fs.copyFileSync(sourceAudioPath, finalAudioPath);\n  } else {\n    const firstBed = musicBeds[0];\n    const bgmPath = safeText(firstBed.filePath);\n    if (!bgmPath || !fs.existsSync(bgmPath)) {\n      throw new Error(`Thiếu file BGM: ${bgmPath || firstBed.bgmId || "unknown"}`);\n    }\n\n    const volume = ensureNumber(firstBed.volume, 0.25);\n    const audioDuration = await readAudioDuration(sourceAudioPath) || ensureNumber(plan.estimatedDuration, 0);\n    const useDuration = ensureNumber(firstBed.duration, 0);\n    const bgmTrim = useDuration > 0 ? useDuration : Math.max(0.1, audioDuration);\n\n    const audioArgs = [\n      "-y",\n      "-i", sourceAudioPath,\n      "-stream_loop", "-1",\n      "-i", bgmPath,\n      "-filter_complex",\n      `[0:a]aformat=sample_fmts=fltp:sample_rates=24000:channel_layouts=mono[voice];` +\n      `[1:a]aformat=sample_fmts=fltp:sample_rates=24000:channel_layouts=mono,atrim=0:${bgmTrim.toFixed(3)},asetpts=PTS-STARTPTS,volume=${volume.toFixed(3)}[bgm];` +\n      `[bgm][voice]sidechaincompress=threshold=0.03:ratio=10:attack=20:release=300:makeup=1[bgmduck];` +\n      `[voice][bgmduck]amix=inputs=2:normalize=0:dropout_transition=0[aout]`,\n      "-map", "[aout]",\n      "-c:a", "pcm_s16le",\n      finalAudioPath\n    ];\n\n    await runFfmpeg(audioArgs);\n  }\n'''
new = '''  if (!musicBeds.length) {\n    fs.copyFileSync(sourceAudioPath, finalAudioPath);\n  } else {\n    const audioDuration = await readAudioDuration(sourceAudioPath) || ensureNumber(plan.estimatedDuration, 0);\n    const validBeds = musicBeds.filter((bed) => {\n      const bgmPath = safeText(bed.filePath);\n      return bgmPath && fs.existsSync(bgmPath);\n    });\n\n    if (!validBeds.length) {\n      fs.copyFileSync(sourceAudioPath, finalAudioPath);\n    } else {\n      const audioArgs = ["-y", "-i", sourceAudioPath];\n      const filterParts = [\n        `[0:a]aformat=sample_fmts=fltp:sample_rates=24000:channel_layouts=mono[voicebase]`\n      ];\n\n      validBeds.forEach((bed) => {\n        audioArgs.push("-stream_loop", "-1", "-i", safeText(bed.filePath));\n      });\n\n      validBeds.forEach((bed, idx) => {\n        const inputIndex = idx + 1;\n        const start = Math.max(0, ensureNumber(bed.start, 0));\n        const volume = Math.max(0, ensureNumber(bed.volume, 0.25));\n        const duration = Math.max(0.1, ensureNumber(bed.duration, 0) || Math.max(0.1, audioDuration - start));\n        filterParts.push(\n          `[${inputIndex}:a]aformat=sample_fmts=fltp:sample_rates=24000:channel_layouts=mono,atrim=0:${duration.toFixed(3)},asetpts=PTS-STARTPTS,adelay=${Math.round(start * 1000)}|${Math.round(start * 1000)},volume=${volume.toFixed(3)}[bgm${idx}]`\n        );\n      });\n\n      const bgmLabels = validBeds.map((_, idx) => `[bgm${idx}]`).join("");\n      if (validBeds.length === 1) {\n        filterParts.push(`${bgmLabels}anull[bgmfull]`);\n      } else {\n        filterParts.push(`${bgmLabels}amix=inputs=${validBeds.length}:normalize=0:dropout_transition=0[bgmfull]`);\n      }\n\n      filterParts.push(`[bgmfull][voicebase]sidechaincompress=threshold=0.03:ratio=10:attack=20:release=300:makeup=1[bgmduck]`);\n      filterParts.push(`[voicebase][bgmduck]amix=inputs=2:normalize=0:dropout_transition=0[aout]`);\n\n      audioArgs.push(\n        "-filter_complex", filterParts.join(";"),\n        "-map", "[aout]",\n        "-c:a", "pcm_s16le",\n        finalAudioPath\n      );\n\n      await runFfmpeg(audioArgs);\n    }\n  }\n'''
text = text.replace(old, new)

# add handlers before app.whenReady maybe locate first app.whenReady
marker = 'app.whenReady().then(async () => {\n'
insert = '''ipcMain.handle("file:list-bgm-assets", async () => {\n  try {\n    const assets = readBgmAssets().map(normalizeBgmAsset);\n    return { ok: true, assets };\n  } catch (error) {\n    return { ok: false, error: error?.message || String(error) };\n  }\n});\n\nipcMain.handle("file:import-bgm-assets", async (_event, payload = {}) => {\n  try {\n    const files = Array.isArray(payload.files) ? payload.files.map((x) => safeText(x)).filter(Boolean) : [];\n    if (!files.length) return { ok: false, error: "Không có file BGM để import." };\n\n    const libraryDir = ensureBgmLibraryDir();\n    const assets = readBgmAssets().map(normalizeBgmAsset);\n    let importedCount = 0;\n\n    for (const src of files) {\n      if (!fs.existsSync(src)) continue;\n      const fileName = path.basename(src);\n      const targetPath = uniqueFilePath(path.join(libraryDir, fileName));\n      fs.copyFileSync(src, targetPath);\n\n      const nextAsset = normalizeBgmAsset({\n        id: path.parse(fileName).name,\n        label: path.parse(fileName).name,\n        fileName: path.basename(targetPath),\n        filePath: targetPath,\n        updatedAt: new Date().toISOString()\n      });\n\n      const existingIndex = assets.findIndex((item) => item.id === nextAsset.id);\n      if (existingIndex >= 0) {\n        assets[existingIndex] = { ...assets[existingIndex], ...nextAsset, createdAt: assets[existingIndex].createdAt || nextAsset.createdAt };\n      } else {\n        assets.push(nextAsset);\n      }\n      importedCount += 1;\n    }\n\n    writeBgmAssets(assets);\n    return { ok: true, assets, importedCount };\n  } catch (error) {\n    return { ok: false, error: error?.message || String(error) };\n  }\n});\n\nipcMain.handle("file:delete-bgm-asset", async (_event, payload = {}) => {\n  try {\n    const assetId = normalizeBgmId(payload.assetId);\n    const assets = readBgmAssets().map(normalizeBgmAsset);\n    const found = assets.find((item) => item.id === assetId);\n    if (found?.filePath && fs.existsSync(found.filePath)) {\n      try { fs.unlinkSync(found.filePath); } catch {}\n    }\n    const next = assets.filter((item) => item.id !== assetId);\n    writeBgmAssets(next);\n    return { ok: true, assets: next };\n  } catch (error) {\n    return { ok: false, error: error?.message || String(error) };\n  }\n});\n\n'''
text = text.replace(marker, insert + marker)

p.write_text(text, encoding='utf-8')

# patch preload
p = Path('/tmp/appfix/electron/preload.cjs')
text = p.read_text(encoding='utf-8')
text = text.replace('  readAudioFile: (payload) => ipcRenderer.invoke("file:read-audio-file", payload),\n  saveAudioFile: (payload) => ipcRenderer.invoke("file:save-audio", payload),\n  listAudioFiles: (payload) => ipcRenderer.invoke("file:list-audio-files", payload),\n\n  convertWaveformVideo: (payload) => ipcRenderer.invoke("file:convert-waveform-video", payload),\n  composeFinalMedia: (payload) => ipcRenderer.invoke("file:compose-final-media", payload)\n});\n', '  readAudioFile: (payload) => ipcRenderer.invoke("file:read-audio-file", payload),\n  saveAudioFile: (payload) => ipcRenderer.invoke("file:save-audio", payload),\n  listAudioFiles: (payload) => ipcRenderer.invoke("file:list-audio-files", payload),\n  listBgmAssets: () => ipcRenderer.invoke("file:list-bgm-assets"),\n  importBgmAssets: (payload) => ipcRenderer.invoke("file:import-bgm-assets", payload),\n  deleteBgmAsset: (payload) => ipcRenderer.invoke("file:delete-bgm-asset", payload),\n\n  convertWaveformVideo: (payload) => ipcRenderer.invoke("file:convert-waveform-video", payload),\n  composeFinalMedia: (payload) => ipcRenderer.invoke("file:compose-final-media", payload)\n});\n')
p.write_text(text, encoding='utf-8')

# patch electronAPI types: add selectAudioFiles if missing
p = Path('/tmp/appfix/electronAPI.d.ts')
text = p.read_text(encoding='utf-8')
text = text.replace('      selectAudioFile: () => Promise<{ canceled: boolean; path: string }>;\n      selectImageFile: () => Promise<{ canceled: boolean; path: string }>;\n', '      selectAudioFile: () => Promise<{ canceled: boolean; path: string }>;\n      selectAudioFiles: () => Promise<{ canceled: boolean; paths: string[] }>;\n      selectImageFile: () => Promise<{ canceled: boolean; path: string }>;\n')
p.write_text(text, encoding='utf-8')

# rewrite start bat
Path('/tmp/appfix/1. Start.bat').write_text('@echo off\r\ncd /d "%~dp0"\r\nnpm run start:all\r\npause\r\n', encoding='utf-8')
